name: custom_calendar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^14.1.1
  flutter_native_timezone: ^2.0.0
  flutter_platform_widgets: ^3.3.1
  flutter_slidable: ^3.0.0
  flutter_spinkit: ^5.2.0
  hydrated_bloc: ^9.1.2
  overlay_support: ^2.1.0
  path_provider: ^2.0.14
  simple_animations: ^5.0.0+3
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - icons/app_icon.png
